set shell := ["powershell", "-Command"]

install:
    python -m venv venv
    source venv/bin/activate # or venv\Scripts\activate on Windows
    pip install -r requirements.txt

run:
    flask --app test.py run --debug

freeze:
    pip freeze > requirements.txt

test:
    pytest